spring:
  datasource:
    username: postgres
    password: geo&0317
    url: jdbc:log4jdbc:postgresql://192.168.45.11:20004/cnbus?prepareThreshold=0 # 릴레이 서버

server:
  address: 127.0.0.1
  port: 8090
  host: 127.0.0.1
  tcp-port: 8091