spring:
  datasource:
    username: tago_module
    password: geon0801
    url: jdbc:log4jdbc:postgresql://192.168.25.21:5432/cnbus?prepareThreshold=0 # 운영 서버

server:
  host: 192.168.60.22
  tcp-port: 8091
  address: 192.168.60.22
  port: 8090

