spring:
  datasource:
    username: tago_module
    password: geon0801
    url: jdbc:log4jdbc:postgresql://192.168.45.11:20010/cnbus?prepareThreshold=0 # 릴레이 서버

server:
  address: 127.0.0.1
  port: 8090
  host: 127.0.0.1
  tcp-port: 8091